<?php

$basePath = Helper::getBasePath();
$menuItems = [
    [
        'name' => 'Начало',
        'url' => 'home',
        'childs' => []
    ],
    [
        'name' => 'Услуги',
        'url' => 'services',
        'childs' => [
            [
                'name' => 'Почивстване на офиси',
                'url' => 'services/office',
            ],
            [
                'name' => 'Почиствае на домове',
                'url' => 'services/home',
            ],
            [
                'name' => 'Пране на килими',
                'url' => 'services/wash',
            ],
            [
                'name' => 'Почистване след ремонт',
                'url' => 'services/renovation-clean',
            ]
        ]
    ],
    [
        'name' => 'Цени',
        'url' => 'prices',
        'childs' => []
    ],
    [
        'name' => 'Контакти',
        'url' => 'contacts',
        'childs' => []
    ],
    [
        'name' => 'Партньори',
        'url' => 'partners',
        'childs' => []
    ],
];
?>

<div class="header-height-push"></div>
<header>
    <div class="header-content-wrapper">
        <h1 class="logo">LinusEin</h1>
        <nav>
            <ul class="first-level-navigation">
                <?php foreach ($menuItems as $menuItem): ?>
                    <li class="first-level-navigation-item <?= $data['viewContentName'] == $menuItem['name']? 'active':'';?>">
                        <span class="first-level-navigation-title">
                            <?php if (empty($menuItem['childs'])): ?>
                                <a href="<?= $basePath . $menuItem['url']; ?>"><?= $menuItem['name']; ?></a>
                            <?php else: ?>
                                <?= $menuItem['name']; ?>
                            <?php endif; ?>
                        </span>
                        <?php if (!empty($menuItem['childs'])): ?>
                            <ul class="second-level-navigation">
                                <?php foreach ($menuItem['childs'] as $secondMenuItemIndex => $secondMenuItem): ?>
                                    <li class="second-level-navigation-item second-level-navigation-item-<?= $secondMenuItemIndex + 1 ; ?>">
                                        <a href="<?= $basePath . $secondMenuItem['url']; ?>"><?= $secondMenuItem['name']; ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>
</header>