<div class="home-wrapper">
    <div class="home-first-section">
        <div class="home-first-section-container">
            <h1 class="home-title">
                Фирма за професионално почистване на домове и офиси.
            </h1>
        </div>
    </div>
    <div class="home-second-section">
        <div class="home-second-section-container">
            <div class="contact-wrapper">
                <div class="contact-container">
                    <h2 class="contact-title">
                        Телефон:
                    </h2>
                    <h3 class="contact-value">
                        0899252672
                    </h3>
                </div>
            </div>
            <div class="contact-wrapper">
                <div class="contact-container">
                    <h2 class="contact-title">
                        Имейл:
                    </h2>
                    <h3 class="contact-value">
                        info@linus-ein.bg
                    </h3>
                </div>
            </div>
            <div class="contact-wrapper">
                <div class="contact-container">
                    <h2 class="contact-title">
                        Работно време:
                    </h2>
                    <h3 class="contact-value">
                        07ч. - 19ч.
                    </h3>
                </div>
            </div>
        </div>
    </div>
    <div class="home-third-section">
        <div class="home-third-section-container">
            <h2 class="third-section-title">
                Видове услуги
            </h2>
            <div class="fancy-cards">
                <div class="fancy-card">
                    <div class="top">
                        <div class="caption">
                            <h3 class="title">Домове</h3>
                            <a href="" class="button">Виж повече</a>
                        </div>
                    </div>
                    <div class="middle"></div>
                    <div class="bottom"></div>
                </div>
                <div class="fancy-card">
                    <div class="top">
                        <div class="caption">
                            <h3 class="title">Офиси</h3>
                            <a href="" class="button">Виж повече</a>
                        </div>
                    </div>
                    <div class="middle"></div>
                    <div class="bottom"></div>
                </div>
                <div class="fancy-card">
                    <div class="top">
                        <div class="caption">
                            <h3 class="title">Килими</h3>
                            <a href="" class="button">Виж повече</a>
                        </div>
                    </div>
                    <div class="middle"></div>
                    <div class="bottom"></div>
                </div>
                <div class="fancy-card">
                    <div class="top">
                        <div class="caption">
                            <h3 class="title">След ремонт</h3>
                            <a href="" class="button">Виж повече</a>
                        </div>
                    </div>
                    <div class="middle"></div>
                    <div class="bottom"></div>
                </div>
            </div>
        </div>
    </div>
</div>